apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 3 # make 3 Pods
  selector:
    matchLabels: # ReplicaSetが管理すべきPodを識別するための条件
      app: httpserver # templateのlabelsと一致している必要がある
      # 一致しないとReplicaSetは「管理すべきPodが見つからない」と判断し、新しいPodを無限に作成しようとします
  template:
    metadata:
      labels: # 新しく作成されるPodに付与されるラベル
        app: httpserver
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
