apiVersion: v1
kind: Service # Podが再起動などで入れ替わってもIPアドレスが変わらないようにするためのもの
metadata:
  name: hello-server-service
spec:
  selector:
    app: hello-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

